const wordList = { 
  Technology: [
    { word: "algorithm", hint: "A step-by-step procedure for solving a problem" },
    { word: "computer", hint: "An electronic device for storing and processing data" },
    { word: "internet", hint: "A global network connecting millions of private and public devices" },
    { word: "keyboard", hint: "An input device used for typing on computers" },
    { word: "monitor", hint: "A device used to display visual output from a computer" },
    { word: "server", hint: "A system that provides data or services to other devices" },
    { word: "database", hint: "An organized collection of data stored electronically" },
    { word: "firewall", hint: "A security system that monitors and controls network traffic" },
    { word: "smartphone", hint: "A mobile phone with advanced computing features" },
    { word: "software", hint: "A set of instructions that tell a computer what to do" },
  ],
  Nature: [
    { word: "sunflower", hint: "A tall plant with a large yellow flower that follows the sun" },
    { word: "jungle", hint: "A dense, tropical forest with abundant wildlife and vegetation" },
    { word: "cactus", hint: "A spiky desert plant known for storing water" },
    { word: "volcano", hint: "A mountain that erupts molten lava from within the Earth's crust" },
    { word: "butterfly", hint: "An insect with colorful wings that undergoes metamorphosis" },
    { word: "penguin", hint: "A flightless bird that lives in cold climates and waddles on land" },
    { word: "island", hint: "A piece of land surrounded by water" },
    { word: "forest", hint: "A large area covered chiefly with trees and undergrowth" },
    { word: "avalanche", hint: "A rapid flow of snow down a mountain slope" },
    { word: "desert", hint: "A barren area of land with little rainfall and sparse vegetation" },
  ],
  Miscellaneous: [
    { word: "treasure", hint: "A collection of valuable items often hidden or buried" },
    { word: "astronaut", hint: "A person trained to travel and work in space" },
    { word: "sandcastle", hint: "A structure built using sand, often by children at the beach" },
    { word: "fireworks", hint: "Explosives used for celebrations, creating colorful lights in the sky" },
    { word: "bicycle", hint: "A two-wheeled vehicle powered by pedaling" },
    { word: "piano", hint: "A large musical instrument with keys played by pressing them" },
    { word: "lantern", hint: "A portable light source, typically enclosed in glass or paper" },
    { word: "puzzle", hint: "A game or problem designed to test ingenuity or knowledge" },
    { word: "umbrella", hint: "A device used to protect against rain or sunlight" },
    { word: "balloon", hint: "A flexible bag that can be inflated with air or gas" },
  ],
  History: [
    { word: "pharaoh", hint: "An ancient Egyptian ruler" },
    { word: "pyramid", hint: "A triangular structure built by ancient civilizations" },
    { word: "renaissance", hint: "A period of cultural revival in Europe during the 14th-17th centuries" },
    { word: "knight", hint: "A mounted soldier in armor serving a feudal lord" },
    { word: "gladiator", hint: "An armed combatant who entertained audiences in ancient Rome" },
    { word: "revolution", hint: "A forcible overthrow of a government or social order" },
    { word: "empire", hint: "A group of countries or regions ruled by one authority" },
    { word: "castle", hint: "A large fortified building or set of buildings" },
    { word: "colosseum", hint: "A large amphitheater in Rome used for public events" },
    { word: "scroll", hint: "A roll of parchment or paper used for writing in ancient times" },
  ],
  Sports: [
    { word: "cricket", hint: "A sport played with a bat and ball, popular in many countries" },
    { word: "basketball", hint: "A sport where players shoot a ball through a hoop" },
    { word: "tennis", hint: "A sport played with a racket and a ball on a rectangular court" },
    { word: "golf", hint: "A sport where players use clubs to hit balls into holes on a course" },
    { word: "boxing", hint: "A combat sport involving two people wearing gloves" },
    { word: "hockey", hint: "A sport where players use sticks to hit a puck or ball into a goal" },
    { word: "karate", hint: "A martial art focused on striking and self-defense" },
    { word: "rugby", hint: "A sport involving an oval ball that can be carried or kicked" },
    { word: "skiing", hint: "A sport involving gliding over snow using skis" },
    { word: "archery", hint: "A sport where arrows are shot at a target using a bow" },
  ],
};
